var res = {
    background_png : "res/back00.jpg",
    star1_png : "res/welcome/start_button.png",

    w_bg:"res/welcome/start_bg.jpg",
    w_title_bg:"res/welcome/title_bg.png",
    w_title:"res/welcome/title.png",

    s_bg:"res/stage/bg.jpg",
    s_creat:"res/stage/creat.jpg",
    s_join:"res/stage/join.png",
    s_join1:"res/stage/join1.png",
    s_join2:"res/stage/join2.png",
    s_join3:"res/stage/join3.png",
    s_join4:"res/stage/join4.png",
    s_join5:"res/stage/join5.png",
    s_join6:"res/stage/join6.png",
    s_join7:"res/stage/join7.png",
    s_join8:"res/stage/join8.png",
    s_join9:"res/stage/join9.png",
    s_join0:"res/stage/join0.png",
    s_joindel:"res/stage/joindel.png",
    s_joinsure:"res/stage/joinsure.png",
    s_joinbg:"res/stage/joinbg.png",
    s_bottom:"res/stage/bottom.png",
    s_huodongbtn:"res/stage/huodongbtn.png",
    s_huodongbg:"res/stage/huodongbg.png",
    s_shopbtn:"res/stage/shopbtn.png",
    s_shopbg:"res/stage/shopbg.png",
    s_shop1:"res/stage/shop1.png",
    s_shop2:"res/stage/shop2.png",
    s_shop3:"res/stage/shop3.png",
    s_shop4:"res/stage/shop4.png",
    s_sharebtn:"res/stage/sharebtn.png",
    s_sharebg:"res/stage/sharebg.png",
    s_scorebtn:"res/stage/scorebtn.png",
    s_systembtn:"res/stage/systembtn.png",
    s_systembg:"res/stage/systembg.png",
    s_rulebtn:"res/stage/rulebtn.png",
    s_rulebg:"res/stage/rulebg.png",
    s_backbtn:"res/stage/backbtn.png",
    s_backbg:"res/stage/backbg.png",
    s_cardbg:"res/stage/cardbg.png",
    s_close:"res/stage/close.png",


    p_bk:"res/play/bk.jpg",
    p_pai0:"res/play/pai/1w.png",
    p_pai1:"res/play/pai/2w.png",
    p_pai2:"res/play/pai/3w.png",
    p_pai3:"res/play/pai/4w.png",
    p_pai4:"res/play/pai/5w.png",
    p_pai5:"res/play/pai/6w.png",
    p_pai6:"res/play/pai/7w.png",
    p_pai7:"res/play/pai/8w.png",
    p_pai8:"res/play/pai/9w.png",
    p_pai9:"res/play/pai/1l.png",
    p_pai10:"res/play/pai/2l.png",
    p_pai11:"res/play/pai/3l.png",
    p_pai12:"res/play/pai/4l.png",
    p_pai13:"res/play/pai/5l.png",
    p_pai14:"res/play/pai/6l.png",
    p_pai15:"res/play/pai/7l.png",
    p_pai16:"res/play/pai/8l.png",
    p_pai17:"res/play/pai/9l.png",
    p_pai18:"res/play/pai/1t.png",
    p_pai19:"res/play/pai/2t.png",
    p_pai20:"res/play/pai/3t.png",
    p_pai21:"res/play/pai/4t.png",
    p_pai22:"res/play/pai/5t.png",
    p_pai23:"res/play/pai/6t.png",
    p_pai24:"res/play/pai/7t.png",
    p_pai25:"res/play/pai/8t.png",
    p_pai26:"res/play/pai/9t.png",
    p_pai27:"res/play/pai/e.png",
    p_pai28:"res/play/pai/s.png",
    p_pai29:"res/play/pai/w.png",
    p_pai30:"res/play/pai/n.png",
    p_pai31:"res/play/pai/z.png",
    p_pai32:"res/play/pai/f.png",
    p_pai33:"res/play/pai/b.png",

    p_ui_center:"res/play/ui/center.png",
    p_ui_back:"res/play/ui/back.png",
    p_ui_info:"res/play/ui/info.png",
    p_ui_header:"res/play/ui/header.png",
    p_ui_rightpai:"res/play/ui/rightpai.png",
    p_ui_backpai:"res/play/ui/backpai.png",
    
    p_ui_choose:"res/play/ui/choose.png",
    p_ui_chooseview_peng:"res/play/ui/peng.png",
    p_ui_chooseview_hu:"res/play/ui/hu.png",
    p_ui_chooseview_gang:"res/play/ui/gang.png",
    p_ui_chooseview_zimo:"res/play/ui/zimo.png",
    p_ui_chooseview_guo_s:"res/play/ui/guo_s.png",
    p_ui_chooseview_hu_b:"res/play/ui/hu_b.png",

    p_win_scorebg:"res/play/win/bg.jpg",
    p_win_title:"res/play/win/title.png",
    p_win_fang:"res/play/win/fang.png",
    p_win_host:"res/play/win/host.png",
    p_win_jie:"res/play/win/jie.png",
    p_win_zhuang:"res/play/win/zhuang.png",

    game_bg:"res/ui/bg.jpg",
    win_bg:"res/ui/win.png",
    create_btn:"res/ui/create_btn.png",
    create_bg:"res/ui/create_bg.png",
    first_meng:"res/ui/meng.png"

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
